#!/bin/sh
. $(dirname $0)/../test_library

set_config() {
  echo "
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [https client]
  client = yes
  accept = 127.0.0.1:${http2}
  connect = 127.0.0.1:${https1}

  [https server]
  accept = 127.0.0.1:${https1}
  connect = 127.0.0.1:${http_nc}
  cert = ${script_path}/certs/server_cert.pem" > "stunnel.conf"
}

change_config() {
#  accept = 127.0.0.1:${http2} -> accept = 127.0.0.1:${http1}
  echo "
  debug = debug
  syslog = no
  pid = ${result_path}/stunnel.pid
  output = ${result_path}/stunnel.log

  [https client]
  client = yes
  accept = 127.0.0.1:${http1}
  connect = 127.0.0.1:${https1}

  [https server]
  accept = 127.0.0.1:${https1}
  connect = 127.0.0.1:${http_nc}
  cert = ${script_path}/certs/server_cert.pem" > "stunnel.conf"
}

start() {
  set_config
  ../../src/stunnel stunnel.conf
}

check_ports "040_reload" "$1" 2>> "stderr.log"
start_stunnel "040_reload" 2> "error.log"
reload_stunnel "040_reload" 2>> "error.log"
test_log_for "040_reload" "success" "$1" 2>> "stderr.log"
exit $?
